default: &default
  username: postgres
  adapter: postgresql
  password: taichigogo
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: igoq_development

test:
  <<: *default
  database: igoq_test

production:
  <<: *default
  database: igoq_production
